name: CI

on:
  push:
    branches:
      - master
      - github-workflow
    tags:
      - "v*"
  # release:
  #   types:
  #   - created

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ] #, '14', '16' ]
    name: Use Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # cache: 'npm'
      # - run: npm install --save-dev
      # - run: npm run vsce-package
      - run: npm install -g vsce
      - run: vsce package # --out ./output

      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v2
        with:
          name: vsix
          path: ./*.vsix
          if-no-files-found: error
          retention-days: 5

      # - name: VSCE Publish
      #   # if: success() && startsWith( github.ref, 'refs/tags/releases/' )
      #   if: success() && startsWith(github.ref, 'refs/tags/v')
      #   run: vsce publish
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    name: Publish to Marketplace
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: npm install -g vsce
      - uses: actions/download-artifact@master
        with:
          name: vsix
          path: ./
      - name: Publish to Marketplace via VSCE
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # https://github.com/softprops/action-gh-release
      - name: Release inside GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: "Release {{ tag_name }}"
          body: "Foo Bar"
        #   body_path: ${{ github.workspace }}-CHANGELOG.txt